### ISSUE TITLE
Initialising a RestClient causes program never to terminate

### ISSUE THREAD

**Issue by brianfoody** [tiagosiebler/ftx-api#32]
Executing this script with `npx ts-node test.ts` for example never terminates.

```
const { RestClient } = require("ftx-api");
const init = async () => {
  new RestClient("credentials.key", "credentials.secret");
};

init()
```

Sample tsconfig.json

```
{
  "compilerOptions": {
    "declaration": true,
    "importHelpers": true,
    "module": "commonjs",
    "outDir": "lib",
    "rootDir": "src",
    "strict": true,
    "target": "es2017"
  },
  "include": [
    "src/**/*"
  ]
}
```

**Comment by tiagosiebler** [comment]
Thanks for including the steps to reproduce. It's probably the time sync timer, which is automatically started when preparing the rest client. You can try to set it to false in the constructor of the rest client:

https://github.com/tiagosiebler/ftx-api/blob/master/src/util/requestUtils.ts#L13

**Comment by Thornsnake** [comment]
What exactly does the time sync do? Fix the few millisecond drift between the Windows clock and the FTX server? Is disabling this feature going to cause any issues in the long run?

Thanks!

**Comment by tiagosiebler** [comment]
> What exactly does the time sync do? Fix the few millisecond drift between the Windows clock and the FTX server? 

Sorry for the late response. Yes, it tries to do exactly this although I'm not convinced on the effectiveness. The time-sync is a mechanism that runs on a timer to estimate latency issues, using that to offset the recv window and attempt to prevent recv window errors due to connection issues outside your control. I'm considering having it disabled by default.

> Is disabling this feature going to cause any issues in the long run?

If you're actively ensuring the following, you should be fine:
- your system time is correctly set (e.g using something like ntp)
- you're handling possible recv errors, as they can still happen sometimes (latency can still cause this for example)
