### ISSUE TITLE
Support for "dust" endpoints

### ISSUE THREAD

**Issue by danielchines** [tiagosiebler/ftx-api#49]
On the FTX website you're able to convert "dust" (coins with a balance less than the `Minimum order size`) to USD on the Wallet page. The closest functionality in the API is the `.../otc/quotes` endpoint which requires you to retrieve a quote for each balance individually.

After looking at the network logs I noticed there's a separate endpoint for "dust" that functions the same as the otc endpoint, except it can convert all balances to USD at once. It's not on their documentation, but this worked for me locally:
https://github.com/tiagosiebler/ftx-api/compare/master...danielchines:dust-endpoint?expand=1

Let me know if I can make a PR

**Comment by tiagosiebler** [comment]
Thanks for this - yes, please do go ahead. Since that endpoint isn't documented, I'd add it to the other "undocumented" endpoints so far: https://github.com/tiagosiebler/ftx-api/blob/master/src/rest-client.ts#L37-L47

Makes it easier to see that they were undocumented discoveries that may have a limited life span.
