### ISSUE TITLE
How can I place futures order with leverage???

### ISSUE THREAD

**Issue by godtaehee** [tiagosiebler/ftx-api#72]
In my case, placeOrder function in RestClient is not working with Leverage

how can I place futures order with leverage????

This order using placeOrder function is always placed with no leverage( 1 X Leverage)

Can you help me???

**Comment by tuloski** [comment]
The leverage is only decided by the amounts you use. FTX is different from every other exchange when using leverages. You should read the documentation on margin trading.
Oh you need to enable margin trading and set leverages in your account to be able to use leverages. I think you can do it via API, but since it's a una-tantum thing you can do it manually logging in.
