### ISSUE TITLE
Use standard params

### ISSUE THREAD

**Issue by tuloski** [tiagosiebler/ftx-api#93]
There are some inconsistencies between params name in the documentation and param names used in this library.
For example getOrderbook() uses "marketName" instead of market_name.
I didn't check all the paraments to have a list of all inconsistencies and maybe this is the only one.

**Comment by tiagosiebler** [comment]
While I see your point, for this method the exact property name doesn't matter since it's passed as part of the URL:
https://github.com/tiagosiebler/ftx-api/blob/master/src/rest-client.ts#L158-L163

Renaming it now from marketName to market_name would also be a breaking change for any of the existing implementations of this connectors. I've tried to be consistent in where I used the camel case convention. Snake case is more of a python thing, the only place where this connector should be using those is if the REST API specifically requires it, e.g. this method where parameters are passed as-is in the request body:
https://github.com/tiagosiebler/ftx-api/blob/master/src/rest-client.ts#L198-L204
